Add js-data + firebase + auth
cassioscabral/rateissuesfront pull request #70
Opened 2016-10-18 18:58 UTC by DominikePessoa

add js-data
add firebase as source
add auth system
add login/logout btn to navigation

2016-10-19 13:45 UTC, cassioscabral requested changes
Changes necessary before merge

2016-10-19 13:45 UTC, cassioscabral commented on src/components/Navigation/navigation.vue
> +        <a v-show="!user" v-on:click="login">login</a>
Prefer to use Vue shorthand syntax. @click instead of v-on:click

2016-10-19 13:45 UTC, cassioscabral commented on src/components/Navigation/navigation.vue
> +        <img v-if="user" v-bind:src="user.photoURL" alt="user image" class="user-avatar" />
Shorthand syntax, use :src instead of v-bind:src

2016-10-19 13:45 UTC, cassioscabral commented on src/components/Navigation/navigation.vue
> +            <a v-on:click="logout">logout</a>
@click instead of v-on:click

2016-10-19 13:45 UTC, cassioscabral commented on src/components/Navigation/navigation.vue
> +import auth from 'src/helpers/auth'
This folder should be only used for general common helpers. Auth files should have their own separated folder.

2016-10-19 13:45 UTC, cassioscabral commented on src/components/Navigation/navigation.vue
> +      user: null
Vue asks that you declare the type of data object before hand. If it's a object should like `user: {}` so it can receive the proper treatment for that data. Arrays should be `[]`, strings `''` and so forth.

2016-10-19 13:45 UTC, cassioscabral commented on src/components/Navigation/navigation.vue
> +import auth from 'src/helpers/auth'
Name it Auth instead of auth, use this as convention. Imported files or component should have a Camel Case pattern so it differentiates from the component data.

2016-10-19 13:45 UTC, cassioscabral commented on src/helpers/auth.js
> +function getGithubAPI () {
Why getGithubAPI ? it returns the token

2016-10-19 13:45 UTC, cassioscabral commented on src/components/Navigation/navigation.vue
> +      auth.login((data) => {this.user = data.user})
Using promises here would be better

2016-10-19 13:45 UTC, cassioscabral commented on src/helpers/auth.js
> +function _signInWithCredential (callback) {
This whole callback approach in this whole file is weird and you should be able to use the promise instead. Returning the promise and dealing with it when necessary. I believe you could make this without using those callback at all.

2016-10-19 13:45 UTC, cassioscabral commented on src/helpers/auth.js
> +  firebase.auth().signInWithPopup(provider).then(function (result) {
Try to use arrows functions if possible.

2016-10-19 13:45 UTC, cassioscabral commented on src/helpers/auth.js
> +    // ...
...

2016-10-19 13:45 UTC, cassioscabral commented on src/helpers/auth.js
> +let user, token
why use those variables outside of the functions ? it makes them all impure, is there a reason for it ? couldn't _getStoredToken return the token when needed ?

2016-10-19 13:45 UTC, cassioscabral commented on src/helpers/auth.js
> +let user, token
The user object should be a responsibility of those who want to know the user. Let's say Navigation, it will call for the user and will receive a promise that as result will provide the user. I think if you decide to cache the user, using storage or whatever you will only check this before doing any other request for the user and provide the cache version instead.

2016-10-19 13:45 UTC, cassioscabral commented on src/helpers/auth.js
> +    token = result.credential.accessToken
why store token in this variable ? that's an example of impure function and is not necessary. If you are using token in other place it makes all even more coupled with that external variable that we don't know when it's being used.

2016-10-19 13:45 UTC, cassioscabral commented on src/helpers/auth.js
> +function _signInWithCredential (callback) {
http://stackoverflow.com/questions/35905599/how-to-use-promise-to-avoid-callback-hell

2016-10-19 13:51 UTC, cassioscabral commented on src/helpers/authStore.js
> +  user: (state) => {return state.user},
could this be `(state) => state.user` ? since is just returning, you could omit the curly brackets and return statement

2016-10-19 13:59 UTC, cassioscabral commented
Check this out http://vuex.vuejs.org/en/state.html

You can pass the store to the app component and it will be accessible throughout the app

2016-10-19 14:21 UTC, cassioscabral commented on src/helpers/authStore.js
> +  user: null,
Initialize the state with a proper representation of what that will be. User should be a object for example.

Check this here: http://vuex.vuejs.org/en/mutations.html#mutations-follow-vues-reactivity-rules

2016-10-20 21:56 UTC, DominikePessoa commented
v-show (and other conditionals) will consider empty objects {} and arrays [] as true.
so, is user becomes {} the v-show need more validation.
like: Object.keys(user).length

https://github.com/vuejs/vue/issues/2217

should I change the null to {}

----

the user is not stored, just the github token.
because, once logged all request will be authenticated.

----

about the impure functions.
all three function manipulate (read, set or remove) the localStorage.
so if I remove the var, I replace for hardcoded string?
maybe I just did not understand the point.

BTW, the code has change. Can you review it?

2016-10-23 20:07 UTC, merged